######################## default configuration ####################
baseURL = "/"
title = "Friends of OpenPGP"
theme = "educenter"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# limit RSS feeds to 50 entries
rssLimit = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/fuse/fuse.js"


############################## navigation ###############################

# main menu
[[menu.main]]
weight = 1
name = "about"
hasChildren = true

  [[menu.main]]
  parent = "about"
  name = "OpenPGP"
  URL = "about/openpgp"
  weight = 1

  [[menu.main]]
  parent = "about"
  name = "FOOPGP"
  URL = "about"
  weight = 2

  [[menu.main]]
  parent = "about"
  name = "partners"
  URL = "partner"
  weight = 4

  [[menu.main]]
  parent = "about"
  name = "friends"
  URL = "author"
  weight = 3

  [[menu.main]]
  parent = "about"
  name = "donate"
  URL = "about/donate"
  weight = 5

  [[menu.main]]
  parent = "about"
  name = "contact"
  URL = "contact"
  weight = 6

[[menu.main]]
name = "solutions"
hasChildren = true
URL = "solutions"
weight = 2

  [[menu.main]]
  parent = "solutions"
  name = "authentication"
  URL = "solutions/theme-authentication"
  weight = 1

  [[menu.main]]
  parent = "solutions"
  name = "encryption"
  URL = "solutions/encryption"
  weight = 2

  [[menu.main]]
  parent = "solutions"
  name = "email"
  URL = "solutions/theme-email"
  weight = 3

  [[menu.main]]
  parent = "solutions"
  name = "identity"
  URL = "solutions/theme-identity"
  weight = 4

  [[menu.main]]
  parent = "solutions"
  name = "vote"
  URL = "solutions/theme-vote"
  weight = 5

  [[menu.main]]
  parent = "solutions"
  name = "payment"
  URL = "solutions/theme-currency"
  weight = 6

[[menu.main]]
name = "trainings"
URL = "course"
weight = 3

[[menu.main]]
weight = 4
name = "events"
URL = "event"

[[menu.main]]
name = "blog"
URL = "blog"
weight = 5

# footer menu

[[menu.footer]]
name = "about"
URL = "about"

[[menu.footer]]
name = "contact"
URL = "contact"

[[menu.footer]]
name = "legal notice"
URL = "about/legal-notice"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Association to promote OpenPGP technologies"
#author = "Themefisher"
# contact info
#address = "9567 Turner Trace Apt. BC C3G8A4"
#mobile = "+211234565523"
email = "info@foopgp.org"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = false
searchURL = "search"

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

############################# social site ########################
#icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons

[[params.social]]
title = "home"
icon = "ti-home" # themify icon : https://themify.me/themify-icons
link = "/"

[[params.social]]
title = "contact"
icon = "ti-email" # themify icon : https://themify.me/themify-icons
link = "mailto:info@foopgp.org"

[[params.social]]
title = "contribute"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/foopgp"

[[params.social]]
title = "donate"
icon = "ti-heart"
link = "/about/donate"

[[params.social]]
title = "follow us"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/foopgp"

[[params.social]]
title = "join us"
icon = "ti-comments" # themify icon : https://themify.me/themify-icons
link = "https://framalistes.org/sympa/info/foopgp"

################################### English language #####################################
[Languages.en]
languageName = "en 🇺🇸 🇬🇧 ..."
languageCode = "en_US"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020. [Thanks](https://github.com/foopgp/foopgp-hugowebsite) to [Hugo](https://gohugo.io) & [themefisher](https://themefisher.com)"


################################### French language #####################################
[Languages.fr]
languageName = "fr 🇫🇷 🇨🇩 ..."
languageCode = "fr_FR"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2020. [Généré](https://github.com/foopgp/foopgp-hugowebsite) grâce à [Hugo](https://gohugo.io) & [themefisher](https://themefisher.com)"
